sphinx_lesson/_static/sphinx_lesson.css
sphinx_lesson/md_transforms.py

- If `<img>` matches `style=*"border:`, then apply the CSS class
`with-border`.
- Define the `with-border` css class to add a 2px solid border
(hardcoded, does not parse the actual style at all).
- The raw directive-based equivalent in markdown is this:
~~~~~~~~
```{figure} /img/doi/publish-release.png
---
class: with-border
---
```
~~~~~~~~

md_transforms: img, parse a border property.

---

conf.py
jupyter.ipynb

- The myst_parser runs on the markdown cells in Jupyter Notebooks, so
that you can use all of the normal directives in there.
- Clarify how you control execution of notebooks.  I got confused when
it wasn't executing when outputs were already present.

jupyter: document recursive myst_parser execution.

---

.github/workflows/sphinx.yml

- Each gh-pages push now makes a new disconnected branch.  This saves
space by discarding history.
- Perhaps the history isn't needed?  But...
- Each branch is built and included in gh-pages, in the
branch/$branch-name/ subdir (except the default branch).  So, that
means we *have* to keep history, or else we lose these branches
(we don't build every branch on every push).  Right now the action
handles that by checking out old gh-pages, inserting the new
build, and pushing.  This change removes that history.
- I'm not sure if there will be some weird interactions and
something will break, but I guess we can try it and see?

.github/workflows/sphinx: Don't keep gh-pages history

---

directives.rst
installation.rst
requirements.txt
sphinx_lesson/__init__.py
sphinx_lesson/directives.py

- Add this extensions as a hard dependency and sets up the `solution`
to start collapsed by default.
- https://github.com/executablebooks/sphinx-togglebutton
- Review: general check unless someone wants to takelocally and
compile it.  A test is in the docs: directives.rst

sphinx-togglebutton: Make solution admonitions collapsed by default

---

sphinx_lesson/_static/sphinx_lesson.css

- These put a colored emoji (instead of the ! icon) in the
admonitions, to highlight the different types.

css: Add emojis for qustions, challenge, solution

---

.github/workflows/sphinx.yml

- This should reduce the window of a race condition when multiple
deploys occur within a short time of each other.  It doesn't
entirely fix it, but should reduce the window in which it can
happen...

.github/workflows/sphinx: Fetch before we branch gh-pages

---

.github/workflows/sphinx.yml

- Strict builds may be desired by some projects
- This adds the option in an easy to find place, but leaves it commented out.

.github/workflows/sphinx: Add commented option for strict builds

---

.github/workflows/sphinx.yml

- This could also be added by Sphinx, but I figure that since we
combine multiple sphinx builds (for the branches), this is the more
appropriate abstraction layer to create the file.
- Review: quick check, does CI pass and it appears in the build?

.github/workflows/sphinx: Add .nojekyll file

---

content/sample-episode-rst.rst

- This is another way to arrange the exercises, which:
- Each group of exercises in its own section
- Each exercise in its own admonition
- Each solution in its own admonition
- This allows direct linking (not currently possible to solitary
admonitions), and exercises to appear in the table of contents.
- Review: discuss if this is a good idea.  If not, close with no
action.

content/sample-episode-rst: Another

---

.github/workflows/release.yml

- This releases via annotated tags, *not* the GitHub release feature.
- As discussed in CodeRefinery #help stream.
- Review: the action works in other places so probably doesn't need to
be reviewed much.

.github/workflows/release: Add gh-action to release

---

content/conf.py
sphinx_lesson/__init__.py

- It was supposed to be enabled, but wasn't.
- Review: does CI pass?

sphinx_lesson/__init__: Enable minipres by default

---

sphinx_lesson/directives.py

- In sphinx_rtd_theme, these become green-colored boxes
- This is an old, uncommitted change: feel free to not use it if best
practice has moved on.
- Review: is this even a good idea for a color scheme?

sphinx_lesson/directives: Make exercises and solutions "important"

---

content/contributing-to-a-lesson.rst
content/index.rst

- If we want to use this widely, we need to explain to others how to
contribute to one of these lessons.  This is designed to be that
page.
- I have avoided repeating things that are explained other places (no
time to re-explain), though eventually these points could be
elaborated (example: how to make a pull request).
- Review:
- This is a quick pass, it is worth reading it carefully and to see
what is wrong or can be simplified.  Though, I am sure it will be
continually improved over time.

content/contributing-to-a-lesson: landing page for contributors

---

content/directives.rst
sphinx_lesson/_static/sphinx_lesson.css
sphinx_lesson/directives.py

- Standardize and color directives as described in #45
- Give various emojis to directives, but not to every one.
- Allow directive content to be empty
- This requires non-trivial (but not too difficult) changes, and may
introduce some maintenance burden.  It may also cause some
incompatility with other themes, but probably not much more than
we already get by our particular styling.
- Improve documentation
- List all directives, how they work, and recommended uses.
- Have a gallery of all directives
- Do not remove carpentries-compatibility directives (and do list
them).
- Review:
- Read #45, and compare these results to that.
- Is this a good implementation?  Good directive names?
- Decide if there is anything to remove or add.
- Is the "empty content" a good idea?
- Are the colors …

Standardize and color directives

---

content/contributing-to-a-lesson.rst

It seems that in some cases use of `python -m venv venv/` instead of `python3`works, so I suggest to add this note. Not sure if the note syntax is successfully rendered (not tried previewing locally), so modify to make it correct. Thanks!

Added a hint when `python3` does not work

---

sphinx_lesson/directives.py

- Some people deriving from this have already use .cssname(), so we
should make life easy and continue to support that.
- Closes: #71
- Review: general check

sphinx_lesson/directives: cssname vs get_cssname backwards compat

---

sphinx_lesson/_static/sphinx_lesson.css

- With sphinx_rtd_theme, when an admonition (sphinx-lesson
terminology: directive) is toggled closed, there is a small amount
of padding at the bottom, where content would be.
- This CSS change removes that padding.
- This is designed to be relatively safe for other themes... but who
knows, it needs checking.  This will be done before merging.

css: for sphinx-togglebutton, remove buffer space in collapsed admonitions

---

content/index.rst
content/indexing.rst

- Indexing allows a structured view into the context.  This can be
useful as a part of a quick reference guide (though the index just
has the terms, not the definitions).
- I'm not sure if many lessons would use this, but it is a nice
feature that we may as well document.  Plus, I did already, but
havn't PRed it, so I may as well do it.
- Review: does the text make general sense?  I have a feeling there
may be some things slightly wrong with it, but I will iterate that
later.

Add description of indexing a lesson using the index directive/role

---

content/exercise-list.rst
content/index.rst
content/installation.rst
sphinx_lesson/__init__.py
sphinx_lesson/directives.py
sphinx_lesson/exerciselist.py

- Add as exercise list directive, as we have found useful for review a lesson and onboarding helpers.
- parses the document, finds the nodes, and adds them to the
- This isn't perfect, but maybe good enough to go and start using for now, and then improve?
For putting it into production (or even testing production), my thought is it is simplest to make a release, and then update our lessons.  I think there should be little risk of breaking lessons that don't use it.

Add exercise list directive

---

content/sample-episode-rst.rst
sphinx_lesson/exerciselist.py

- This prevents duplicate solutions in the list, when a solution is
included as part of the exercise, and as a separate one.
- Not yet perfect, it doesn't look at higher level parents.
- Review: does CI pass?  Test with another lesson or two.

exerciselist: exclude nodes whose parent is included

---

.github/workflows/test.yml
sphinx_lesson/exerciselist.py

- Sphinx 4.0 renamed master_doc to root_doc, so exerciselist didn't
work on that earlier version.
- The Github Action actually does try to test for earlier versions,
but it seems like it does n't successfully install the older Sphinx
versions for the tests.  Re-adjust the action to install everything
at once, in hopes that this works.  A local test implies that it
might.
- Closes: #84
- Review:
- does CI pass?
- Check the action output "List dependency version" log and verify
that it's testing older sphinx versions.

exerciselist: Support sphinx<4.0, which uses master_doc instead of root_doc

---

content/exercise-list.rst
content/sample-episode-rst.rst
sphinx_lesson/exerciselist.py

- If we make a copy of the nodes we re-insert
(`exercise_node.copy()`), the error goes away.
- Interestingly, the error stays when you use either
`exercise_node.deepcopy()` or `copy.deepcopy(exercise_node)`.
- First pushing without the fix to ensure CI sees the error, then will
force-push with the fix.
- Closes: #83
- Review:
- If anyone knows sphinx/docutils well, take a look.  But
realistically, that may be no one so merge if CI passes.

content/sample-episode-rst: Fix 'pending_xref' error with links in exercise list

---

.github/workflows/sphinx.yml
.github/workflows/test.yml
content/conf.py
content/indexing.rst
content/intersphinx.rst
requirements.txt

- A four-part version fails with sphinx_rtd_theme:
https://github.com/readthedocs/sphinx_rtd_theme/issues/1343 While
this is a problem with sphinx_rtd_theme, the easiest solution is to
limit Sphinx version (sphinx_rtd_theme updates *slowly*)
- This should be reverted after either sphinx releases again with a
more normal version number, or sphinx_rtd_theme updates.
- Review: see if CI passes

requirements: Prohibit Sphinx 5.2.0.post0

---

content/indexing.rst
content/intersphinx.rst

- To avoid confusing, Sphinx 5.0 avoids looking up documents in other
projects with a role of `:std:doc:`.  What this means that if you
link to `` :std:doc:`glossary` ``, it might accidentally link to
`glossary` in one of the external projects.  The new idea is that
you wouldn't usually want to link directly to an external page (this
is not symbolic and could be rearranged at any time).  Instead, link
to the symbolic description, e.g. `` :rst:dir:`glossary` ``.  The
exactly function/directive/etc. is a stable link which is good to
link to.  (you could say this is the same reason we don't want to
use raw HTML links)
- Change the few :std:doc: external links to the rst directives that
we *actually* meant to link to.
- This change should work in older Sphinx just as well.  This was
probably …

Fix sphinx 5.0 ignoring :std:doc: links by default

---

.github/workflows/sphinx.yml
.github/workflows/test.yml

- python 3.6, 3.8, latest (3.10 right now)
- sphinx 3.0 and greater (5.0 was just released)
- Review: this will be merged as part of another change

CI: Update versions used to test

---

content/conf.py

- This is the new option name, and since we run with strict mode
(warnings become errors) we need to fix this.
- This doesn't affect lessons since they don't get built in strict
mode.
- This requires myst_nb 0.16.0 (2022-06-13)
- Review: must be used as part of other changes to make CI pass

content/conf: jupyter_execute_notebooks -> nb_execution_mode

---

content/sample-episode-rst.rst

- A example of the discussion directive was missing from the sample
episode.
- Review: automerge

content/sample-episode-rst: Add `discussion` example

---

sphinx_lesson/directives.py

- Right now, the `discussion` directive is derived from `attention`,
so is **yellow*.
- Most other directives that want you to actively do something are
**green** (derived from 'important') - and this was the idea.
- I think it makes more sense for `discussion` to be the "do
something" color (green like exercises) rather than yellow like
`warning`/`attention`.  This makes that change
- Review:
- Check out the directive gallery
(https://coderefinery.github.io/sphinx-lesson/directives/#gallery)
and see if `discussion` should rather be green, rather than
yellow.
- For reasoning of the current color scheme, read
https://coderefinery.github.io/sphinx-lesson/directives/#gallery

directives: Derive the discussion directive from 'important', not 'attention'

---

.github/workflows/test.yml
content/intersphinx.rst

- Fixes CI failures (tests silently failed before because of yaml
syntax - how is that even possible?!)

.github/workflows/test: Exclude CI matrix for old sphinx+new python

---

content/exercise-list.rst
sphinx_lesson/exerciselist.py

- Allow a user to specify which admonitions should be inlcuded or
excluded
- Also refactors the exerciselist mechanics to make this possible,
which allows for each exercise list to be different.
- Review: check docs, I'll look at this again and merge

exerciselist: allow selecting admonitions to include/exclude

---

content/conf.py

This fixes the link to the MyST execution modes in comments of conf.py file.

Fix link to MyST notebook execution modes

---

content/building.md
content/changelog.md
content/cheatsheet.md
content/conf.py
content/contributing-to-a-lesson.md
content/convert-old-lessons.md
content/executing-code.md
content/exercise-list.md
content/getting-started.md
content/gh-action.md
content/index.md
content/indexing.md
content/installation.md
content/intersphinx.md
content/jupyter.ipynb
content/md-and-rst.md
content/md-transforms.rst
content/substitutions-replacements.md
content/toctree.md

- Emphasize MyST by putting those examples first and making sure they
are everywhere.
- Various other small text updates to say what is old and no longer
needed.
- Various other small wording changes where needed.
- Review: automerge

Emphasize MyST, various other improvements

---

sphinx_lesson/_static/sphinx_lesson.css

Use a custom selection background and foreground color
