requirements.txt, sphinx_lesson/__init__.py
- This should add a copy button to all code blocks.  A quick local
test shows it works.
- Not yet documented or any more serious tests...
=> Add sphinx_copybutton extension

.github/workflows/test.yml, conf.py
- Use github actions to test that the code works
=> gh-actions to actually test the lesson

getting-started.rst, index.rst, installation.rst
- Improvenments mainly about how to get started with a new lesson
- To review: general or no check, iteration will continue either
way.
=> Improve docs some

conf.py, sphinx_lesson/__init__.py
- Extension returns its actual version
- Docs built and lists the actual version
- Review: not much if tests pass, though one can check if this is a
good strategy.
=> Handle versions better

conf.py
- This is just to help others who may want to enable this later, in
their own projects.
- Also needs copying into the repository template.  Could also be put
into docs.
- Review: general sanity check that this is useful.
=> conf: add intersphinx template (but commented so not in use)

content/gh-action.rst, content/index.rst, content/installation.rst
- A little bit of info, but it could use much, much more.
- Review: depending on interest, either little or merge and improve
later.  This isn't intended to be the final docs on the matter.
=> gh-action: add minimal documentation on our github action

content/convert-old-lessons.rst
- It's getting easier and easier, almost painless.
- Review: a more detailed read is worth it, but this is still an
incremental change.
=> content/convert-old-lessons: Further refine the conversion steps

content/conf.py, requirements.txt
=> Add sphinx_rtd_theme_ext_color_contrast

content/changelog.rst, content/index.rst
- No real content yet, just prototype of the changelog so far.
- Review: minimal necessary
=> changelog: initial version of changelog

content/getting-started.rst, content/installation.rst
- In response to @eglerean pointing out we need better getting started
docs.  This updates to mention the different ways of getting
started,and explicitely pointing out the best template repositry to
use.
- Review: general read, do things make sense?
=> getting started docs: improve some

content/conf.py
- Review: does CI pass and is preview OK?
=> content/conf: Add RTD theme github button

README.rst
- Code blocks can be introduced with `::` and then intented
- Review: general check / CI passes?
=> README: Update RST syntax

content/installation.rst, requirements.txt, sphinx_lesson/__init__.py
- This is a really cool extension: https://sphinx-tabs.readthedocs.io/
- No documentation yet, can be added later
- Review: do we want sphinx-tabs as default?
=> requirements: Add sphinx-tabs as default extension

content/convert-old-lessons.rst
=> content/convert-old-lessons: update location of conf.py

.gitignore
=> .gitignore: Update with jupyter stuff

README.rst
- Since it was hard to find
- Review: does CI pass?
=> README: Link template repository

sphinx_lesson/_static/sphinx_lesson.css
Taken from https://emojipedia.org/
=> Use code points for emojis

.github/workflows/sphinx.yml
- Comments in the source explain how this works
- Tested in the enccs/intermediate-mpi repo
- Review: minimal
=> .github/workflows/sphinx: Add workaround for url-root

.github/workflows/sphinx.yml
- Link to the sphinx-lesson issue as well, in the comment describing
the workaround.
- Closes: #50
- Review: minimal check
=> .github/workflows/sphinx: Add comment on url-root fix

content/conf.py, content/index.rst, content/intersphinx.rst
- New page, intersphinx
- Add some more useful examples in conf.pyy
- Review: general check, already tested in another lesson.
=> Add docs for how Intersphinx references works

.github/workflows/sphinx.yml
I have synced the `sphinx.yml` workflow with the one in `sphinx-lesson-template`. I've added a snippet to get the name of the default branch: it should hopefully help  with the `master` -> `main` renaming.
=> Sync with template, handle default branch

content/building.rst, content/md-and-rst.rst, content/sample-episode-rst.rst
- Various small docs fixes, I made in the progress of doing other changes.
- Review: general check
=> Various docs fixes

setup.py
=> setup: Add "project_urls" key with link to project documentation

content/exercise-list.rst
- Clarify what makes for good exercises descriptions (is is good?)
- Mention `challenge` directives also.
- Review: general check
=> content/exercise-list: Update docs

sphinx_lesson/exerciselist.py
- Previous fix didn't work, it resulted in empty exerciselists
- The core problem is that, before all the internal links are
resolved, they are sphinx.addnodes.pending_xref nodes.  These are
used to record "this will be an internal reference", and are
resolved later, once all the pages are read in (since clearly, some
can't be resolved if the other pages are not yet read in)
- After several other attempts, inserting the transform hook in a
different place (as a post_transform, not doctree-resolved), it
seems that I can insert the nodes before the cross-references get
resolved, and then things work.
- Review: someone who knows sphinx internals could check it out, but
realistically that is just me.  I will merge when I check the
results and hope for the best.
=> exerciselist: Fix 'pending_xref' nodes missing by transforming earlier

content/sample-episode-rst.rst
- Based on "lessons learned" and things I have seen, update the sample
with best practices
- Review: automerge and review rendered version
=> content/sample-episode-rst: Update sample episode based on recent lessons
